### ISSUE TITLE
EditText doesn't open with ImeOptions

### ISSUE THREAD

**Issue by LionelCremer** [florent37/MaterialTextField#10]
I've 2 MaterialTextField, the first one has the following attribute: ime_options="actionNext".
But when I click on the button "Next", after having filled my first EditText, the second MaterialTextField doesn't open automatically.

**Comment by florent37** [comment]
fixed in 1.0.6

**Comment by weibsons** [comment]
I have the same problem with version 1.0.7.
I needed downgrade version for 1.0.6
