### ISSUE TITLE
Where is the cornerRadius on these textfields?

### ISSUE THREAD

**Issue by Odaym** [florent37/MaterialTextField#12]
I really want to have the implementation look like what you posted in the README, because [this is ugly ](https://dl.dropboxusercontent.com/u/19390574/Screenshot_2016-05-12-13-24-42.png)

here's my XML for achieving the above

            <com.github.florent37.materialtextfield.MaterialTextField
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:mtf_cardCollapsedHeight="@dimen/material_textfield_collapsed_height"
                app:mtf_image="@drawable/ic_email_black_24dp"
                app:mtf_labelColor="@android:color/black"
                app:mtf_openKeyboardOnFocus="true">

                <com.andreabaccega.widget.FormEditText
                    android:id="@+id/emailET"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:hint="@string/email_address_hint"
                    android:inputType="textEmailAddress"
                    android:singleLine="true"
                    android:textColor="@android:color/black"
                    android:textColorHint="@color/edittext_hint_color"
                    android:textCursorDrawable="@null"
                    validator:emptyErrorString="@string/field_empty_error_message"
                    validator:testErrorString="@string/error_email_address_not_valid"
                    validator:testType="email"/>

            </com.github.florent37.materialtextfield.MaterialTextField>

**Comment by Odaym** [comment]
Note that the purple background is just for seeing whether there actually was any radius on the corners or not, wouldn't have showed properly if no white

**Comment by florent37** [comment]
sorry, please try with the 1.0.4 I changed it 👍

**Comment by Odaym** [comment]
thanks for the quick response, that indeed fixed it, you edited the 9patch?

**Comment by florent37** [comment]
I removed the 9patch and added a shape drawable :D
