### ISSUE TITLE
doesn't work on ~10" Sony Tablet S (Android 4.0.3)

### ISSUE THREAD

**Issue by kasim1011** [florent37/MaterialTextField#13]
after updating to version 1.0.4 it doesn't work on ~10" Sony Tablet S (Android 4.0.3).

![screenshot_2016-05-17-11-54-28](https://cloud.githubusercontent.com/assets/7657803/15313308/1d2624bc-1c28-11e6-9f88-a29693b53efc.png)

Expand doesn't work properly. please, fix these ASAP. Thanks

**Comment by florent37** [comment]
can you try with the 1.0.5 ?

**Comment by kasim1011** [comment]
Great! it works now.
Thanks a lot Sir,
