### ISSUE TITLE
Improper implementation on pre-lollipop devices

### ISSUE THREAD

**Issue by edwinkr2000** [florent37/MaterialTextField#3]
Hi, there seems to be a problem with implementation on pre-lollipop devices, the text hint appears to be obscured by the cardview
![screenshot_2015-08-29-00-13-24](https://cloud.githubusercontent.com/assets/11136242/9557528/7b9fd48c-4de5-11e5-982f-6e27b072bec5.png)

**Comment by florent37** [comment]
I fixed it in the 1.0.2 :+1:
