### ISSUE TITLE
bug in Tablet, 7" and up

### ISSUE THREAD

**Issue by tellfa** [florent37/MaterialTextField#5]
hi, tnx for this library but i can't use this in tablet ! in under 7" devices its perfect but up 7" devices show big bug !
please show this image, Tablet 7".
how to fix it bug?  i really need this library .

tnx

**Comment by florent37** [comment]
can you try with the new version please ?

**Comment by tellfa** [comment]
Hi, in new version fixed that bug my bro :heart:

**Comment by florent37** [comment]
👍

**Comment by kasim1011** [comment]
after updating to version 1.0.4 it still doesn't work on 7" Sony Tablet S (Android 4.0.3).

![screenshot_2016-05-17-11-54-28](https://cloud.githubusercontent.com/assets/7657803/15313308/1d2624bc-1c28-11e6-9f88-a29693b53efc.png)

Expand doesn't work properly. please, fix these ASAP. Thanks
