### ISSUE TITLE
Text going behind edittext on api 16

### ISSUE THREAD

**Issue by bhargavms** [florent37/MaterialTextField#7]
https://owncloud.talview.com/index.php/s/VAhzFfrVPNOxeZA

As you can see from the screenshot above, the hint text is going inside the minimized edittext for api 16, please tell me how to fix this

**Comment by madhu2b4u** [comment]
Yes i am facing same issue..

Any solution ?

**Comment by bhargavms** [comment]
Update to the latest version I apologize for not posting the solution, and closing the issue. The problem is the version provided by the author in the readme is outdated

**Comment by Frange** [comment]
Thank's for the answer.

**Comment by florent37** [comment]
should be fine with the new version ;)
