### ISSUE TITLE
app:mtf_cardCollapsedHeight="4dp" Property Not working

### ISSUE THREAD

**Issue by tutysathish** [florent37/MaterialTextField#8]
The Above property not working for me android 4.4.4

**Comment by yawboafo** [comment]
Experiencing the same

**Comment by H03in** [comment]
I have same problem :|

**Comment by florent37** [comment]
should be fine with the new version ;)

**Comment by H03in** [comment]
Tanks  a lot!

**Comment by issacchern** [comment]
Still, when collapsing, the horizontal lines is removed.

**Comment by Crepusculo** [comment]
The problem still exist there

**Comment by hangng** [comment]
From:
compile 'com.github.florent37:materialtextfield:1.0.5' 

To: 
compile 'com.github.florent37:materialtextfield:1.0.1'

it worked for me ;)
